package.json
resolver-keys.json

https://linear.app/unstoppable-domains/issue/SUP-375

[SUP-375] feat: Add YLD to resolver list

---

resolver-keys.json

Fixed a small typo in information['description'].

Fix typo in description

---

CHANGELOG.md
package.json
resolver-keys.json

🐶 https://linear.app/unstoppable-domains/issue/SUP-391/add-dollardog-the-doge-nft-token-record 🐶

Add DOG token

---

CHANGELOG.md
package.json
resolver-keys.json

https://linear.app/unstoppable-domains/issue/ECUX-310/new-currency-support-b2m

[ECUX-310] feat: Add new currency support: B2M

---

CHANGELOG.md
package.json
resolver-keys.json

https://linear.app/unstoppable-domains/issue/SUP-396/new-currency-support-gala-coin

[SUP-396] feat: Add `GALA` currency support

---

CHANGELOG.md
package.json
resolver-keys.json

Addresses https://linear.app/unstoppable-domains/issue/SUP-430/new-currency-support-mobx
Incremented version to 0.5.10 based on the changelog.

[SUP-430] Add MOBX support

---

CHANGELOG.md
package.json
scripts/build_dotcoin_upgrade_list.js

* Added script to fetch on-chain tokens
* Updated package version, changelog

REG-610: added script to fetch .coin tokens

---

.github/workflows/contracts_size.yml
hardhat.config.js

Action will calculate the difference in size between the source and target branches.
Example with Delta value > 0: https://github.com/unstoppabledomains/uns/pull/163#issuecomment-1253644896
GitHub action: https://github.com/unstoppabledomains/solidity-sizer

[REG-641]: Action to add contracts size information to the PR

---

CHANGELOG.md

[ECH-520](https://linear.app/unstoppable-domains/issue/ECH-520/klever-address-validation-problem-on-mobile-website) - fix: klever address regex is not working right. Needs to be changed. 
* Changes
- .klever regex is updated. 
- package.json and resolver-keys.json versions are increased. 
```
```
```
```
```
```
- [] `resolver-keys.json` code review is required from **DevTools** team

[ECH-520] - Fixing .klever address validation regex.

---

.openzeppelin/mainnet.json
.openzeppelin/polygon.json
CHANGELOG.md
package.json
uns-config.json

[REG-597] Deployment mainnets 

---

.openzeppelin/goerli.json
.openzeppelin/mainnet.json
.openzeppelin/polygon-mumbai.json
.openzeppelin/polygon.json
CHANGELOG.md
package.json
scripts/upgrade_ProxyReader.ts
uns-config.json

[REG-733] Deploy ProxyReader@0.4.0

---

sandbox/index.test.ts
scripts/build_blocklist.ts
scripts/build_dotcoin_upgrade_list.ts
scripts/configure_UNS_Polygon_POS_Bridge.ts
scripts/deploy.ts
scripts/deploy_CNS_Forwarders.ts
scripts/deploy_DotCoinBurner.ts
scripts/deploy_MintingManagerForwarder.ts
scripts/deploy_Polygon_POS_Bridge.ts
scripts/deploy_ProxyReader.ts
scripts/deploy_UNS.ts
scripts/deploy_UNS_only.ts
scripts/deploy_full.ts
scripts/temp_dotcoin_upgrade.ts
scripts/temp_tlds_reconfigure_l1.ts
scripts/temp_tlds_reconfigure_l2.ts
scripts/upgrade.ts
scripts/upgrade_MintingManager.ts
scripts/upgrade_ProxyReader.ts
scripts/upgrade_UNSRegistry.ts
src/config.ts

Scripts cleanup

---

CHANGELOG.md
package.json
resolver-keys.json

Linear tickets: 
https://linear.app/unstoppable-domains/issue/ECH-493/new-currency-support-sui
https://linear.app/unstoppable-domains/issue/ECH-478/new-currency-support-moon
```
```
```
```
```
```

[ECH-493] Add SUI and MOON tokens

---

.openzeppelin/goerli.json
.openzeppelin/mainnet.json
.openzeppelin/polygon-mumbai.json
.openzeppelin/polygon.json
CHANGELOG.md
package.json
uns-config.json

[REG-725][REG-726] Update contracts

---

.openzeppelin/goerli.json
.openzeppelin/polygon-mumbai.json
CHANGELOG.md
package.json
src/tasks.ts
uns-config.json

[REG-824] Deployment subdomains issue bugfix to testnets

---

.openzeppelin/goerli.json
.openzeppelin/polygon-mumbai.json
CHANGELOG.md
package.json
src/tasks.ts
uns-config.json

[REG-837] - Deploy unhashing updates to Goerli and Mumbai testnets

---

CHANGELOG.md
package.json
sandbox/ganache-service.ts
sandbox/index.test.ts
sandbox/index.ts
sandbox/rebuild.ts

Revert to legacy ganache options

---

.openzeppelin/mainnet.json
.openzeppelin/polygon.json
CHANGELOG.md
package.json
uns-config.json

[REG-825] Deploy subdomains issue bugfix to mainnets

---

test/consumption/UNSRegistry.reverse.gas.test.ts

[REG-839] - Add subdomains to gas estimations for setReverse(string[]) usage

---

CHANGELOG.md
package.json
resolver-keys.json

[ECH-689] Fix LSK regex

---

CHANGELOG.md

[REG-881] - Update changelog

---

.openzeppelin/goerli.json
.openzeppelin/mainnet.json
.openzeppelin/polygon-mumbai.json
.openzeppelin/polygon.json
CHANGELOG.md
package.json
uns-config.json

[REG-895] Upgrade MintingManager@0.4.13

---

.openzeppelin/polygon-mumbai.json
CHANGELOG.md
package.json
src/tasks.ts
uns-config.json

[REG-933] chore: Mumbai Upgrade

---

CHANGELOG.md
package.json
uns-config.json

[REG-934] Update versions

---

CHANGELOG.md
package.json
resolver-keys.json

Requested revision from Partner Engineering.
These are incorrectly marked as Legacy
```
```

[ECH-815] Remove deprecation of Railgun currencies

---

.openzeppelin/goerli.json
.openzeppelin/polygon-mumbai.json
CHANGELOG.md
package.json
src/tasks.ts
uns-config.json

[REG-977] chore: Upgrade ProxyReader on testnets

---

.openzeppelin/goerli.json
CHANGELOG.md
ens-config.json
package.json
scripts/deploy_ENSCustody.ts

[REG-996] Deploy ENSCustody on Goerli

---

scripts/blockchain_families.csv

[REG-1021] chore: Reconfigured ProxyReader on testnets

---

.openzeppelin/mainnet.json
.openzeppelin/polygon.json
CHANGELOG.md
package.json
uns-config.json

[REG-978] Upgrade ProxyReader on Mainnet

---

CHANGELOG.md
package.json
resolver-keys.json

https://linear.app/unstoppable-domains/issue/DT-1311/update-wallet-address-validation-for-sui
```
```

chore: update SUI token regex

---

.openzeppelin/goerli.json
.openzeppelin/mainnet.json
CHANGELOG.md
ens-config.json
package.json

[REG-1072] Upgraded ENSCustody 

---

.github/pull_request_template.md
.prettierrc
ens-resolver-keys.json
package.json
scripts/generate_ens-resolver-keys.ts
yarn.lock

feat: add ens-resolver-keys.json

---

.openzeppelin/polygon-mumbai.json
.openzeppelin/polygon.json
CHANGELOG.md
package.json
uns-config.json

[REG-1106]: Upgraded MintingManager on Mumbai and Polygon

---

.openzeppelin/polygon-mumbai.json
.openzeppelin/polygon.json
CHANGELOG.md
package.json
uns-config.json

[REG-1106]: Upgraded MintingManager@0.4.18 on Mumbai and Polygon mainnet

---

CHANGELOG.md
ens-resolver-keys.json
package.json
resolver-keys.json

This PR updates incorrect validation regexes for a series of tokens. This was a [result of a manual QA](https://docs.google.com/spreadsheets/d/1F7bK-KVqb7TuQTQu0HAD-dF55HTTE5-S4DkAWJ8vs2c/edit?usp=sharing) on our end.
```
```

[ECW-2933] Update validation regex across a set of tokens

---

CHANGELOG.md
ens-resolver-keys.json
package.json

This is a quick follow-up PR to update `ADA` token inside ENS resolver keys config.
```
```

Update ADA ENS token validation regex

---

CHANGELOG.md
package.json
resolver-keys.json

This PR updates `ERG` UNS token validation regex to a correct one: https://regex101.com/r/mt0xNr/1
```
```

[ECW-2933] Update ERG UNS token validation regex

---

package.json

Updated package json version for release

---

CHANGELOG.md
package.json
resolver-keys.json

[ECW 3008] Add NIBI token

---

.openzeppelin/polygon-mumbai.json
CHANGELOG.md
package.json
uns-config.json

[REG-1239] Upgraded Registry and MintingManager on mumbai

---

CHANGELOG.md
package.json
uns-config.json

[REG-1248] fixed deployment block for predicate on sepolia

---

.openzeppelin/polygon.json
CHANGELOG.md
package.json
uns-config.json

[REG-1240] Upgraded UNSRegistry and MintingManager on Polygon

---

CHANGELOG.md
package.json
scripts/util/deploy_ERC1271SimpleWallet.ts
tsconfig.json

add helpful util script for deploying ERC1271SimpleWallet, no contract changes

add helpful util script for deploying ERC1271SimpleWallet

---

.github/workflows/release.yml

[REG-1273] - Fix release github action task

---

.openzeppelin/polygon.json
CHANGELOG.md
package.json
uns-config.json

[REG-1297] - Deploy SeaportProxyBuyer to mainnet

---

CHANGELOG.md
package.json
resolver-keys.json

Symbol: FARMS
Blockchain: Polygon
Logo/Icon (.svg file type): png below
Validation regex (if known): standard polygon address
Scanner: https://polygonscan.com/token/0xf2da37643c25ca14291c2a69f51423ed9b7ff4b0
CMC: https://coinmarketcap.com/currencies/farmsent/
```
```

[ECW-3477] Add FARMS token into resolver list

---

CHANGELOG.md
package.json
src/tlds.ts

Hotfix: make .pw expirable in tlds config

---

CHANGELOG.md
package.json
scripts/batchMintTlds.ts
src/defender.ts
yarn.lock

[REG-1555] Batch Mint TLD script

---

.github/workflows/contracts_size.yml
.github/workflows/main.yml
.github/workflows/release.yml

[REG-1633] Fix CI

---

CHANGELOG.md
dist/uns-config.json
package.json
uns-config.json

[REG-1745] uns-config fix for Sonic

---

CHANGELOG.md
package.json
scripts/schemaState/146-blockchain-families-state.json
scripts/schemaState/57054-blockchain-families-state.json

[REG-1745] Sonic blockchain families

---

CHANGELOG.md
package.json
yarn.lock

Quick ethers version update
